 
<?php $posts = $this->getPosts(); ?>
<div id="messages_product_view">
    <?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?> 
    <?php echo Mage::app()->getLayout()->getMessagesBlock()->getGroupedHtml(); ?> 
</div>

 <?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
<?php foreach ($posts as $post): ?>
   <!-- post --> 
<?php
$html= $post->getPostContent();

$html=str_replace('{{media url="', Mage::getBaseUrl('media'),$html);
$html=str_replace('"}}', "",$html);

if (preg_match('/<img.+?src(?: )*=(?: )*[\'"](.*?)[\'"]/si', $html, $arrResult)) {
    $image = '<img src="'.$arrResult[1].'"/>';
}

$post_content = strip_tags($html,'<p><br><strong><i><b>');

?>
    <div class="postWrapper">
        <div class="postImage"><?php echo $image; ?></div>
        <div class="postContentArea">
            <div class="postTitle">
                <h2><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h2>
            </div>
            <div class="line"></div>
            <div class="postContent"><?php echo $post_content; ?></div>
        </div>
        <div class="clear"></div>
        <div class="postInfo clearfix">
            <div class="leftInfo">
                <div class="user"><?php echo $post->getUser(); ?></div>
                <div class="date"><?php echo $post->getCreatedTime(); ?></div>
            </div>
            <div class="centerInfo">
                <div class="category"><?php $postCats = $post->getCats(); ?>
            <?php if (!empty($postCats)): ?>
                <?php echo $this->__('Published in: '); ?>
                <?php foreach ($postCats as $data): ?>               
                    <a href="<?php echo $data['url']; ?>"><?php echo $data['title']; ?></a> 
                <?php endforeach; ?> 
            <?php else: ?>
                <?php echo $this->__('Published in: Blog'); ?>
            <?php endif; ?></div>
                <?php if($this->getTagsHtml($post)<>'') {  echo '<div class="tags">'.$this->__('Tags: ');  echo $this->getTagsHtml($post).'</div>'; } ?>
            </div>
            <div class="rightInfo">
                <div class="comments"><?php echo $this->__('Comments: '); ?><?php echo $post->getCommentCount(); ?></div>
                <div class="readmore"><a class="button" href="<?php echo $post->getAddress(); ?>" ><?php echo $this->__('Read more'); ?></a></div>
            </div>
        </div>
        
        
    </div>
<!-- /post --> 
<?php endforeach; ?> 

 <?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
<?php //$this->getPages(); ?>
