<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
    $now = date("Y-m-d H:m:s");     
    $use_zoom = themeOptions('use_zoom'); 
    $use_carousel = themeOptions('use_carousel');
    $thumbs_count = count($this->getGalleryImages());
    $_i_thumbs = 0;
?>
<?php 

    $_mainWidth = 412;
    $_mainHeight = 517;
    $_smWidth = 128;
    $_smHeight = 128;
    $_carWidth = 412;
    $_zoomLeft = $_mainWidth + 17;
    $_zoomWidth = themeOptions('zoom_width');        

?>
<style>
    .product-view .product-img-box .more-views { width:<?php echo $_carWidth ?>px; }
    #zoom-window { left: <?php echo $_zoomLeft ?>px; width: <?php echo $_zoomWidth ?>px; }
</style>
<div class="zoom-container layout_default">
    
    <?php include('labels.phtml') ?>
    <div class="main-image" >   
        <a id="zoom" class="<?php if(!$use_zoom): ?> swipebox<?php endif;?> main-thumbnail" href="<?php echo $this->helper('catalog/image')->init($_product, 'image') ?>">
            <?php
                $_img = '<img class="zoom-image" src="'.$this->helper('catalog/image')->init($_product, 'image')->resize($_mainWidth,$_mainHeight).'" width="'.$_mainWidth.'" height="'.$_mainHeight.'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
                echo $_helper->productAttribute($_product, $_img, 'image');
            ?>
        </a> 
        <?php if($use_zoom): ?>
        
            <a id="zoom" class="lightbox-btn" href="<?php echo $this->helper('catalog/image')->init($_product, 'image') ?>">+</a>        
        
        <?php endif;?>
    </div> 
  
    <div class="more-views" <?php if($use_carousel && $thumbs_count > 3): ?>style="height:130px;"<?php endif; ?>>
        <div class="zoom-gallery slider">
	
        <?php if($thumbs_count == 0): ?>
            <div class="slide last">
                <a class="zoom-thumbnail<?php if(!$use_zoom): ?> swipebox<?php endif;?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'image') ?>" data-easyzoom-source="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize($_mainWidth,$_mainHeight) ?>">
                    <?php
                        $_img = '<img class="zoom-image" src="'.$this->helper('catalog/image')->init($_product, 'thumbnail')->resize($_smWidth,$_smHeight).'" width="'.$_smWidth.'" height="'.$_smHeight.'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
                        echo $_helper->productAttribute($_product, $_img, 'image');
                    ?>
                </a>   
            </div>   
        <?php endif; ?>
	
        <?php if ($thumbs_count > 0): ?>  
            <?php foreach ($this->getGalleryImages() as $_image): $_i_thumbs++; ?>
                <div class="slide <?php if($thumbs_count == $_i_thumbs) echo 'last'; ?>">
                    <a rel="gallery-1" class="zoom-thumbnail<?php if(!$use_zoom): ?> swipebox<?php endif;?>"  href="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile()); ?>" data-easyzoom-source="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize($_mainWidth,$_mainHeight); ?>" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>"><img class="fade-image" src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize($_smWidth,$_smHeight); ?>" width="<?php echo $_smWidth ?>" height="<?php echo $_smHeight ?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" /></a>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>
        </div>              
    </div>
    <?php if($use_carousel && $thumbs_count > 0): ?>
        <div class="more-views-arrow prev">&nbsp;</div>
        <div class="more-views-arrow next">&nbsp;</div>                 
    <?php endif;?>  
</div>    
    <?php if($use_carousel && $thumbs_count <= 3): ?>
    <style>
    @media only screen and (min-width: 1001px) {
	.more-views-arrow {
	    display:none;
	}
    }
    </style>
    <?php if($use_carousel && $thumbs_count <= 2): ?>
    <style>
    @media only screen and (min-width: 481px) {
	.more-views-arrow {
	    display:none;
	}
    }
    </style>
    <?php endif;?>
     <?php if($use_carousel && $thumbs_count <= 1): ?>
    <style>
    @media only screen and (max-width: 480px) {
	.more-views-arrow {
	    display:none;
	}
    }
    </style>
    <?php endif;?>
    <?php endif;?>  
	<script type="text/javascript">    
    	
    <?php if($use_zoom) { ?>
        // Start easyZoom
    	jQuery('#zoom')
    		.easyZoom({
    			parent: 'div.zoom-container',
    			preload: '',
                lightboxBtn: '.lightbox-btn'
    		})
    		.data('easyZoom')
    		.gallery('a.zoom-thumbnail');
    <?php } else { ?>
	jQuery(".swipebox").swipebox();
    <?php } ?>
    <?php if($use_carousel && $thumbs_count > 0): ?>	 
        jQuery('.more-views').iosSlider({
            desktopClickDrag: true,
            snapToChildren: true,
            infiniteSlider: false,
            navNextSelector: '.more-views-arrow.next',
            navPrevSelector: '.more-views-arrow.prev'
        });                         
    <?php endif;?>
    
     // Start lightbox
    
	jQuery(".lightbox-btn").click(function(e){
	       e.preventDefault();
	       jQuery.swipebox([
			
		        <?php $_i_thumbs = 0; foreach ($this->getGalleryImages() as $_image): $_i_thumbs++;
			if($_i_thumbs < count($this->getGalleryImages()))
			{
			    echo '{href:"'.$this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile()).'", title:"'.$_helper->productAttribute($_product, $_product->getName(), 'name').' / '.$_i_thumbs.'"},';
			}
			else
			{
			    echo '{href:"'.$this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile()).'", title:"'.$_helper->productAttribute($_product, $_product->getName(), 'name').' / '.$_i_thumbs.'"}';
			}
                   
		   endforeach; ?>
	       ]);
       });
	
	jQuery(function(){
      jQuery(document.body)
          .on('click touchend','#swipebox-slider .current img', function(e){
              return false;
          })
          .on('click touchend','#swipebox-slider .current', function(e){
              jQuery('#swipebox-close').trigger('click');
          });
    });
	
	</script>
	<?php if(!$use_carousel): ?>
	<style>
	.more-views {
	    height:auto;
	}
	.product-view .product-img-box .more-views .slide:nth-child(3n) {
	    margin-right:0px;
	}
	.product-view .product-img-box .more-views .slide {
	    margin-bottom:12px;
	}
	</style>
	<?php endif; ?>
