<?php class ThemeAdminPanel_ExtraConfig_Model_Googlefont
{
    public function toOptionArray()
    {
        return array(
            array('value'=>'Arial', 'label'=>Mage::helper('ExtraConfig')->__('Arial (Disable Google Font)')),
            array('value'=>'ABeeZee:regular,italic', 'label'=>Mage::helper('ExtraConfig')->__('ABeeZee')),
array('value'=>'Abel:regular', 'label'=>Mage::helper('ExtraConfig')->__('Abel')),
array('value'=>'Abril Fatface:regular', 'label'=>Mage::helper('ExtraConfig')->__('Abril Fatface')),
array('value'=>'Aclonica:regular', 'label'=>Mage::helper('ExtraConfig')->__('Aclonica')),
array('value'=>'Acme:regular', 'label'=>Mage::helper('ExtraConfig')->__('Acme')),
array('value'=>'Actor:regular', 'label'=>Mage::helper('ExtraConfig')->__('Actor')),
array('value'=>'Adamina:regular', 'label'=>Mage::helper('ExtraConfig')->__('Adamina')),
array('value'=>'Advent Pro:100,200,300,regular,500,600,700', 'label'=>Mage::helper('ExtraConfig')->__('Advent Pro')),
array('value'=>'Aguafina Script:regular', 'label'=>Mage::helper('ExtraConfig')->__('Aguafina Script')),
array('value'=>'Akronim:regular', 'label'=>Mage::helper('ExtraConfig')->__('Akronim')),
array('value'=>'Aladin:regular', 'label'=>Mage::helper('ExtraConfig')->__('Aladin')),
array('value'=>'Aldrich:regular', 'label'=>Mage::helper('ExtraConfig')->__('Aldrich')),
array('value'=>'Alegreya:regular,italic,700,700italic,900,900italic', 'label'=>Mage::helper('ExtraConfig')->__('Alegreya')),
array('value'=>'Alegreya SC:regular,italic,700,700italic,900,900italic', 'label'=>Mage::helper('ExtraConfig')->__('Alegreya SC')),
array('value'=>'Alex Brush:regular', 'label'=>Mage::helper('ExtraConfig')->__('Alex Brush')),
array('value'=>'Alfa Slab One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Alfa Slab One')),
array('value'=>'Alice:regular', 'label'=>Mage::helper('ExtraConfig')->__('Alice')),
array('value'=>'Alike:regular', 'label'=>Mage::helper('ExtraConfig')->__('Alike')),
array('value'=>'Alike Angular:regular', 'label'=>Mage::helper('ExtraConfig')->__('Alike Angular')),
array('value'=>'Allan:regular,700', 'label'=>Mage::helper('ExtraConfig')->__('Allan')),
array('value'=>'Allerta:regular', 'label'=>Mage::helper('ExtraConfig')->__('Allerta')),
array('value'=>'Allerta Stencil:regular', 'label'=>Mage::helper('ExtraConfig')->__('Allerta Stencil')),
array('value'=>'Allura:regular', 'label'=>Mage::helper('ExtraConfig')->__('Allura')),
array('value'=>'Almendra:regular,italic,700,700italic', 'label'=>Mage::helper('ExtraConfig')->__('Almendra')),
array('value'=>'Almendra Display:regular', 'label'=>Mage::helper('ExtraConfig')->__('Almendra Display')),
array('value'=>'Almendra SC:regular', 'label'=>Mage::helper('ExtraConfig')->__('Almendra SC')),
array('value'=>'Amarante:regular', 'label'=>Mage::helper('ExtraConfig')->__('Amarante')),
array('value'=>'Amaranth:regular,italic,700,700italic', 'label'=>Mage::helper('ExtraConfig')->__('Amaranth')),
array('value'=>'Amatic SC:regular,700', 'label'=>Mage::helper('ExtraConfig')->__('Amatic SC')),
array('value'=>'Amethysta:regular', 'label'=>Mage::helper('ExtraConfig')->__('Amethysta')),
array('value'=>'Anaheim:regular', 'label'=>Mage::helper('ExtraConfig')->__('Anaheim')),
array('value'=>'Andada:regular', 'label'=>Mage::helper('ExtraConfig')->__('Andada')),
array('value'=>'Andika:regular', 'label'=>Mage::helper('ExtraConfig')->__('Andika')),
array('value'=>'Angkor:regular', 'label'=>Mage::helper('ExtraConfig')->__('Angkor')),
array('value'=>'Annie Use Your Telescope:regular', 'label'=>Mage::helper('ExtraConfig')->__('Annie Use Your Telescope')),
array('value'=>'Anonymous Pro:regular,italic,700,700italic', 'label'=>Mage::helper('ExtraConfig')->__('Anonymous Pro')),
array('value'=>'Antic:regular', 'label'=>Mage::helper('ExtraConfig')->__('Antic')),
array('value'=>'Antic Didone:regular', 'label'=>Mage::helper('ExtraConfig')->__('Antic Didone')),
array('value'=>'Antic Slab:regular', 'label'=>Mage::helper('ExtraConfig')->__('Antic Slab')),
array('value'=>'Anton:regular', 'label'=>Mage::helper('ExtraConfig')->__('Anton')),
array('value'=>'Arapey:regular,italic', 'label'=>Mage::helper('ExtraConfig')->__('Arapey')),
array('value'=>'Arbutus:regular', 'label'=>Mage::helper('ExtraConfig')->__('Arbutus')),
array('value'=>'Arbutus Slab:regular', 'label'=>Mage::helper('ExtraConfig')->__('Arbutus Slab')),
array('value'=>'Architects Daughter:regular', 'label'=>Mage::helper('ExtraConfig')->__('Architects Daughter')),
array('value'=>'Archivo Black:regular', 'label'=>Mage::helper('ExtraConfig')->__('Archivo Black')),
array('value'=>'Archivo Narrow:regular,italic,700,700italic', 'label'=>Mage::helper('ExtraConfig')->__('Archivo Narrow')),
array('value'=>'Arimo:regular,italic,700,700italic', 'label'=>Mage::helper('ExtraConfig')->__('Arimo')),
array('value'=>'Arizonia:regular', 'label'=>Mage::helper('ExtraConfig')->__('Arizonia')),
array('value'=>'Armata:regular', 'label'=>Mage::helper('ExtraConfig')->__('Armata')),
array('value'=>'Artifika:regular', 'label'=>Mage::helper('ExtraConfig')->__('Artifika')),
array('value'=>'Arvo:regular,italic,700,700italic', 'label'=>Mage::helper('ExtraConfig')->__('Arvo')),
array('value'=>'Asap:regular,italic,700,700italic', 'label'=>Mage::helper('ExtraConfig')->__('Asap')),
array('value'=>'Asset:regular', 'label'=>Mage::helper('ExtraConfig')->__('Asset')),
array('value'=>'Astloch:regular,700', 'label'=>Mage::helper('ExtraConfig')->__('Astloch')),
array('value'=>'Asul:regular,700', 'label'=>Mage::helper('ExtraConfig')->__('Asul')),
array('value'=>'Atomic Age:regular', 'label'=>Mage::helper('ExtraConfig')->__('Atomic Age')),
array('value'=>'Aubrey:regular', 'label'=>Mage::helper('ExtraConfig')->__('Aubrey')),
array('value'=>'Audiowide:regular', 'label'=>Mage::helper('ExtraConfig')->__('Audiowide')),
array('value'=>'Autour One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Autour One')),
array('value'=>'Average:regular', 'label'=>Mage::helper('ExtraConfig')->__('Average')),
array('value'=>'Average Sans:regular', 'label'=>Mage::helper('ExtraConfig')->__('Average Sans')),
array('value'=>'Averia Gruesa Libre:regular', 'label'=>Mage::helper('ExtraConfig')->__('Averia Gruesa Libre')),
array('value'=>'Averia Libre:300,300italic,regular,italic,700,700italic', 'label'=>Mage::helper('ExtraConfig')->__('Averia Libre')),
array('value'=>'Averia Sans Libre:300,300italic,regular,italic,700,700italic', 'label'=>Mage::helper('ExtraConfig')->__('Averia Sans Libre')),
array('value'=>'Averia Serif Libre:300,300italic,regular,italic,700,700italic', 'label'=>Mage::helper('ExtraConfig')->__('Averia Serif Libre')),
array('value'=>'Bad Script:regular', 'label'=>Mage::helper('ExtraConfig')->__('Bad Script')),
array('value'=>'Balthazar:regular', 'label'=>Mage::helper('ExtraConfig')->__('Balthazar')),
array('value'=>'Bangers:regular', 'label'=>Mage::helper('ExtraConfig')->__('Bangers')),
array('value'=>'Basic:regular', 'label'=>Mage::helper('ExtraConfig')->__('Basic')),
array('value'=>'Battambang:regular,700', 'label'=>Mage::helper('ExtraConfig')->__('Battambang')),
array('value'=>'Baumans:regular', 'label'=>Mage::helper('ExtraConfig')->__('Baumans')),
array('value'=>'Bayon:regular', 'label'=>Mage::helper('ExtraConfig')->__('Bayon')),
array('value'=>'Belgrano:regular', 'label'=>Mage::helper('ExtraConfig')->__('Belgrano')),
array('value'=>'Belleza:regular', 'label'=>Mage::helper('ExtraConfig')->__('Belleza')),
array('value'=>'BenchNine:300,regular,700', 'label'=>Mage::helper('ExtraConfig')->__('BenchNine')),
array('value'=>'Bentham:regular', 'label'=>Mage::helper('ExtraConfig')->__('Bentham')),
array('value'=>'Berkshire Swash:regular', 'label'=>Mage::helper('ExtraConfig')->__('Berkshire Swash')),
array('value'=>'Bevan:regular', 'label'=>Mage::helper('ExtraConfig')->__('Bevan')),
array('value'=>'Bigelow Rules:regular', 'label'=>Mage::helper('ExtraConfig')->__('Bigelow Rules')),
array('value'=>'Bigshot One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Bigshot One')),
array('value'=>'Bilbo:regular', 'label'=>Mage::helper('ExtraConfig')->__('Bilbo')),
array('value'=>'Bilbo Swash Caps:regular', 'label'=>Mage::helper('ExtraConfig')->__('Bilbo Swash Caps')),
array('value'=>'Bitter:regular,italic,700', 'label'=>Mage::helper('ExtraConfig')->__('Bitter')),
array('value'=>'Black Ops One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Black Ops One')),
array('value'=>'Bokor:regular', 'label'=>Mage::helper('ExtraConfig')->__('Bokor')),
array('value'=>'Bonbon:regular', 'label'=>Mage::helper('ExtraConfig')->__('Bonbon')),
array('value'=>'Boogaloo:regular', 'label'=>Mage::helper('ExtraConfig')->__('Boogaloo')),
array('value'=>'Bowlby One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Bowlby One')),
array('value'=>'Bowlby One SC:regular', 'label'=>Mage::helper('ExtraConfig')->__('Bowlby One SC')),
array('value'=>'Brawler:regular', 'label'=>Mage::helper('ExtraConfig')->__('Brawler')),
array('value'=>'Bree Serif:regular', 'label'=>Mage::helper('ExtraConfig')->__('Bree Serif')),
array('value'=>'Bubblegum Sans:regular', 'label'=>Mage::helper('ExtraConfig')->__('Bubblegum Sans')),
array('value'=>'Bubbler One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Bubbler One')),
array('value'=>'Buda:300', 'label'=>Mage::helper('ExtraConfig')->__('Buda')),
array('value'=>'Buenard:regular,700', 'label'=>Mage::helper('ExtraConfig')->__('Buenard')),
array('value'=>'Butcherman:regular', 'label'=>Mage::helper('ExtraConfig')->__('Butcherman')),
array('value'=>'Butterfly Kids:regular', 'label'=>Mage::helper('ExtraConfig')->__('Butterfly Kids')),
array('value'=>'Cabin:regular,italic,500,500italic,600,600italic,700,700italic', 'label'=>Mage::helper('ExtraConfig')->__('Cabin')),
array('value'=>'Cabin Condensed:regular,500,600,700', 'label'=>Mage::helper('ExtraConfig')->__('Cabin Condensed')),
array('value'=>'Cabin Sketch:regular,700', 'label'=>Mage::helper('ExtraConfig')->__('Cabin Sketch')),
array('value'=>'Caesar Dressing:regular', 'label'=>Mage::helper('ExtraConfig')->__('Caesar Dressing')),
array('value'=>'Cagliostro:regular', 'label'=>Mage::helper('ExtraConfig')->__('Cagliostro')),
array('value'=>'Calligraffitti:regular', 'label'=>Mage::helper('ExtraConfig')->__('Calligraffitti')),
array('value'=>'Cambo:regular', 'label'=>Mage::helper('ExtraConfig')->__('Cambo')),
array('value'=>'Candal:regular', 'label'=>Mage::helper('ExtraConfig')->__('Candal')),
array('value'=>'Cantarell:regular,italic,700,700italic', 'label'=>Mage::helper('ExtraConfig')->__('Cantarell')),
array('value'=>'Cantata One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Cantata One')),
array('value'=>'Cantora One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Cantora One')),
array('value'=>'Capriola:regular', 'label'=>Mage::helper('ExtraConfig')->__('Capriola')),
array('value'=>'Cardo:regular,italic,700', 'label'=>Mage::helper('ExtraConfig')->__('Cardo')),
array('value'=>'Carme:regular', 'label'=>Mage::helper('ExtraConfig')->__('Carme')),
array('value'=>'Carrois Gothic:regular', 'label'=>Mage::helper('ExtraConfig')->__('Carrois Gothic')),
array('value'=>'Carrois Gothic SC:regular', 'label'=>Mage::helper('ExtraConfig')->__('Carrois Gothic SC')),
array('value'=>'Carter One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Carter One')),
array('value'=>'Caudex:regular,italic,700,700italic', 'label'=>Mage::helper('ExtraConfig')->__('Caudex')),
array('value'=>'Cedarville Cursive:regular', 'label'=>Mage::helper('ExtraConfig')->__('Cedarville Cursive')),
array('value'=>'Ceviche One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Ceviche One')),
array('value'=>'Changa One:regular,italic', 'label'=>Mage::helper('ExtraConfig')->__('Changa One')),
array('value'=>'Chango:regular', 'label'=>Mage::helper('ExtraConfig')->__('Chango')),
array('value'=>'Chau Philomene One:regular,italic', 'label'=>Mage::helper('ExtraConfig')->__('Chau Philomene One')),
array('value'=>'Chela One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Chela One')),
array('value'=>'Chelsea Market:regular', 'label'=>Mage::helper('ExtraConfig')->__('Chelsea Market')),
array('value'=>'Chenla:regular', 'label'=>Mage::helper('ExtraConfig')->__('Chenla')),
array('value'=>'Cherry Cream Soda:regular', 'label'=>Mage::helper('ExtraConfig')->__('Cherry Cream Soda')),
array('value'=>'Cherry Swash:regular,700', 'label'=>Mage::helper('ExtraConfig')->__('Cherry Swash')),
array('value'=>'Chewy:regular', 'label'=>Mage::helper('ExtraConfig')->__('Chewy')),
array('value'=>'Chicle:regular', 'label'=>Mage::helper('ExtraConfig')->__('Chicle')),
array('value'=>'Chivo:regular,italic,900,900italic', 'label'=>Mage::helper('ExtraConfig')->__('Chivo')),
array('value'=>'Cinzel:regular,700,900', 'label'=>Mage::helper('ExtraConfig')->__('Cinzel')),
array('value'=>'Cinzel Decorative:regular,700,900', 'label'=>Mage::helper('ExtraConfig')->__('Cinzel Decorative')),
array('value'=>'Clicker Script:regular', 'label'=>Mage::helper('ExtraConfig')->__('Clicker Script')),
array('value'=>'Coda:regular,800', 'label'=>Mage::helper('ExtraConfig')->__('Coda')),
array('value'=>'Coda Caption:800', 'label'=>Mage::helper('ExtraConfig')->__('Coda Caption')),
array('value'=>'Codystar:300,regular', 'label'=>Mage::helper('ExtraConfig')->__('Codystar')),
array('value'=>'Combo:regular', 'label'=>Mage::helper('ExtraConfig')->__('Combo')),
array('value'=>'Comfortaa:300,regular,700', 'label'=>Mage::helper('ExtraConfig')->__('Comfortaa')),
array('value'=>'Coming Soon:regular', 'label'=>Mage::helper('ExtraConfig')->__('Coming Soon')),
array('value'=>'Concert One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Concert One')),
array('value'=>'Condiment:regular', 'label'=>Mage::helper('ExtraConfig')->__('Condiment')),
array('value'=>'Content:regular,700', 'label'=>Mage::helper('ExtraConfig')->__('Content')),
array('value'=>'Contrail One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Contrail One')),
array('value'=>'Convergence:regular', 'label'=>Mage::helper('ExtraConfig')->__('Convergence')),
array('value'=>'Cookie:regular', 'label'=>Mage::helper('ExtraConfig')->__('Cookie')),
array('value'=>'Copse:regular', 'label'=>Mage::helper('ExtraConfig')->__('Copse')),
array('value'=>'Corben:regular,700', 'label'=>Mage::helper('ExtraConfig')->__('Corben')),
array('value'=>'Courgette:regular', 'label'=>Mage::helper('ExtraConfig')->__('Courgette')),
array('value'=>'Cousine:regular,italic,700,700italic', 'label'=>Mage::helper('ExtraConfig')->__('Cousine')),
array('value'=>'Coustard:regular,900', 'label'=>Mage::helper('ExtraConfig')->__('Coustard')),
array('value'=>'Covered By Your Grace:regular', 'label'=>Mage::helper('ExtraConfig')->__('Covered By Your Grace')),
array('value'=>'Crafty Girls:regular', 'label'=>Mage::helper('ExtraConfig')->__('Crafty Girls')),
array('value'=>'Creepster:regular', 'label'=>Mage::helper('ExtraConfig')->__('Creepster')),
array('value'=>'Crete Round:regular,italic', 'label'=>Mage::helper('ExtraConfig')->__('Crete Round')),
array('value'=>'Crimson Text:regular,italic,600,600italic,700,700italic', 'label'=>Mage::helper('ExtraConfig')->__('Crimson Text')),
array('value'=>'Croissant One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Croissant One')),
array('value'=>'Crushed:regular', 'label'=>Mage::helper('ExtraConfig')->__('Crushed')),
array('value'=>'Cuprum:regular,italic,700,700italic', 'label'=>Mage::helper('ExtraConfig')->__('Cuprum')),
array('value'=>'Cutive:regular', 'label'=>Mage::helper('ExtraConfig')->__('Cutive')),
array('value'=>'Cutive Mono:regular', 'label'=>Mage::helper('ExtraConfig')->__('Cutive Mono')),
array('value'=>'Damion:regular', 'label'=>Mage::helper('ExtraConfig')->__('Damion')),
array('value'=>'Dancing Script:regular,700', 'label'=>Mage::helper('ExtraConfig')->__('Dancing Script')),
array('value'=>'Dangrek:regular', 'label'=>Mage::helper('ExtraConfig')->__('Dangrek')),
array('value'=>'Dawning of a New Day:regular', 'label'=>Mage::helper('ExtraConfig')->__('Dawning of a New Day')),
array('value'=>'Days One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Days One')),
array('value'=>'Delius:regular', 'label'=>Mage::helper('ExtraConfig')->__('Delius')),
array('value'=>'Delius Swash Caps:regular', 'label'=>Mage::helper('ExtraConfig')->__('Delius Swash Caps')),
array('value'=>'Delius Unicase:regular,700', 'label'=>Mage::helper('ExtraConfig')->__('Delius Unicase')),
array('value'=>'Della Respira:regular', 'label'=>Mage::helper('ExtraConfig')->__('Della Respira')),
array('value'=>'Denk One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Denk One')),
array('value'=>'Devonshire:regular', 'label'=>Mage::helper('ExtraConfig')->__('Devonshire')),
array('value'=>'Didact Gothic:regular', 'label'=>Mage::helper('ExtraConfig')->__('Didact Gothic')),
array('value'=>'Diplomata:regular', 'label'=>Mage::helper('ExtraConfig')->__('Diplomata')),
array('value'=>'Diplomata SC:regular', 'label'=>Mage::helper('ExtraConfig')->__('Diplomata SC')),
array('value'=>'Domine:regular,700', 'label'=>Mage::helper('ExtraConfig')->__('Domine')),
array('value'=>'Donegal One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Donegal One')),
array('value'=>'Doppio One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Doppio One')),
array('value'=>'Dorsa:regular', 'label'=>Mage::helper('ExtraConfig')->__('Dorsa')),
array('value'=>'Dosis:200,300,regular,500,600,700,800', 'label'=>Mage::helper('ExtraConfig')->__('Dosis')),
array('value'=>'Dr Sugiyama:regular', 'label'=>Mage::helper('ExtraConfig')->__('Dr Sugiyama')),
array('value'=>'Droid Sans:regular,700', 'label'=>Mage::helper('ExtraConfig')->__('Droid Sans')),
array('value'=>'Droid Sans Mono:regular', 'label'=>Mage::helper('ExtraConfig')->__('Droid Sans Mono')),
array('value'=>'Droid Serif:regular,italic,700,700italic', 'label'=>Mage::helper('ExtraConfig')->__('Droid Serif')),
array('value'=>'Duru Sans:regular', 'label'=>Mage::helper('ExtraConfig')->__('Duru Sans')),
array('value'=>'Dynalight:regular', 'label'=>Mage::helper('ExtraConfig')->__('Dynalight')),
array('value'=>'EB Garamond:regular', 'label'=>Mage::helper('ExtraConfig')->__('EB Garamond')),
array('value'=>'Eagle Lake:regular', 'label'=>Mage::helper('ExtraConfig')->__('Eagle Lake')),
array('value'=>'Eater:regular', 'label'=>Mage::helper('ExtraConfig')->__('Eater')),
array('value'=>'Economica:regular,italic,700,700italic', 'label'=>Mage::helper('ExtraConfig')->__('Economica')),
array('value'=>'Electrolize:regular', 'label'=>Mage::helper('ExtraConfig')->__('Electrolize')),
array('value'=>'Elsie:regular,900', 'label'=>Mage::helper('ExtraConfig')->__('Elsie')),
array('value'=>'Elsie Swash Caps:regular,900', 'label'=>Mage::helper('ExtraConfig')->__('Elsie Swash Caps')),
array('value'=>'Emblema One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Emblema One')),
array('value'=>'Emilys Candy:regular', 'label'=>Mage::helper('ExtraConfig')->__('Emilys Candy')),
array('value'=>'Engagement:regular', 'label'=>Mage::helper('ExtraConfig')->__('Engagement')),
array('value'=>'Englebert:regular', 'label'=>Mage::helper('ExtraConfig')->__('Englebert')),
array('value'=>'Enriqueta:regular,700', 'label'=>Mage::helper('ExtraConfig')->__('Enriqueta')),
array('value'=>'Erica One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Erica One')),
array('value'=>'Esteban:regular', 'label'=>Mage::helper('ExtraConfig')->__('Esteban')),
array('value'=>'Euphoria Script:regular', 'label'=>Mage::helper('ExtraConfig')->__('Euphoria Script')),
array('value'=>'Ewert:regular', 'label'=>Mage::helper('ExtraConfig')->__('Ewert')),
array('value'=>'Exo:100,100italic,200,200italic,300,300italic,regular,italic,500,500italic,600,600italic,700,700italic,800,800italic,900,900italic', 'label'=>Mage::helper('ExtraConfig')->__('Exo')),
array('value'=>'Expletus Sans:regular,italic,500,500italic,600,600italic,700,700italic', 'label'=>Mage::helper('ExtraConfig')->__('Expletus Sans')),
array('value'=>'Fanwood Text:regular,italic', 'label'=>Mage::helper('ExtraConfig')->__('Fanwood Text')),
array('value'=>'Fascinate:regular', 'label'=>Mage::helper('ExtraConfig')->__('Fascinate')),
array('value'=>'Fascinate Inline:regular', 'label'=>Mage::helper('ExtraConfig')->__('Fascinate Inline')),
array('value'=>'Faster One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Faster One')),
array('value'=>'Fasthand:regular', 'label'=>Mage::helper('ExtraConfig')->__('Fasthand')),
array('value'=>'Federant:regular', 'label'=>Mage::helper('ExtraConfig')->__('Federant')),
array('value'=>'Federo:regular', 'label'=>Mage::helper('ExtraConfig')->__('Federo')),
array('value'=>'Felipa:regular', 'label'=>Mage::helper('ExtraConfig')->__('Felipa')),
array('value'=>'Fenix:regular', 'label'=>Mage::helper('ExtraConfig')->__('Fenix')),
array('value'=>'Finger Paint:regular', 'label'=>Mage::helper('ExtraConfig')->__('Finger Paint')),
array('value'=>'Fjalla One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Fjalla One')),
array('value'=>'Fjord One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Fjord One')),
array('value'=>'Flamenco:300,regular', 'label'=>Mage::helper('ExtraConfig')->__('Flamenco')),
array('value'=>'Flavors:regular', 'label'=>Mage::helper('ExtraConfig')->__('Flavors')),
array('value'=>'Fondamento:regular,italic', 'label'=>Mage::helper('ExtraConfig')->__('Fondamento')),
array('value'=>'Fontdiner Swanky:regular', 'label'=>Mage::helper('ExtraConfig')->__('Fontdiner Swanky')),
array('value'=>'Forum:regular', 'label'=>Mage::helper('ExtraConfig')->__('Forum')),
array('value'=>'Francois One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Francois One')),
array('value'=>'Freckle Face:regular', 'label'=>Mage::helper('ExtraConfig')->__('Freckle Face')),
array('value'=>'Fredericka the Great:regular', 'label'=>Mage::helper('ExtraConfig')->__('Fredericka the Great')),
array('value'=>'Fredoka One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Fredoka One')),
array('value'=>'Freehand:regular', 'label'=>Mage::helper('ExtraConfig')->__('Freehand')),
array('value'=>'Fresca:regular', 'label'=>Mage::helper('ExtraConfig')->__('Fresca')),
array('value'=>'Frijole:regular', 'label'=>Mage::helper('ExtraConfig')->__('Frijole')),
array('value'=>'Fruktur:regular', 'label'=>Mage::helper('ExtraConfig')->__('Fruktur')),
array('value'=>'Fugaz One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Fugaz One')),
array('value'=>'GFS Didot:regular', 'label'=>Mage::helper('ExtraConfig')->__('GFS Didot')),
array('value'=>'GFS Neohellenic:regular,italic,700,700italic', 'label'=>Mage::helper('ExtraConfig')->__('GFS Neohellenic')),
array('value'=>'Gafata:regular', 'label'=>Mage::helper('ExtraConfig')->__('Gafata')),
array('value'=>'Galdeano:regular', 'label'=>Mage::helper('ExtraConfig')->__('Galdeano')),
array('value'=>'Galindo:regular', 'label'=>Mage::helper('ExtraConfig')->__('Galindo')),
array('value'=>'Gentium Basic:regular,italic,700,700italic', 'label'=>Mage::helper('ExtraConfig')->__('Gentium Basic')),
array('value'=>'Gentium Book Basic:regular,italic,700,700italic', 'label'=>Mage::helper('ExtraConfig')->__('Gentium Book Basic')),
array('value'=>'Geo:regular,italic', 'label'=>Mage::helper('ExtraConfig')->__('Geo')),
array('value'=>'Geostar:regular', 'label'=>Mage::helper('ExtraConfig')->__('Geostar')),
array('value'=>'Geostar Fill:regular', 'label'=>Mage::helper('ExtraConfig')->__('Geostar Fill')),
array('value'=>'Germania One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Germania One')),
array('value'=>'Gilda Display:regular', 'label'=>Mage::helper('ExtraConfig')->__('Gilda Display')),
array('value'=>'Give You Glory:regular', 'label'=>Mage::helper('ExtraConfig')->__('Give You Glory')),
array('value'=>'Glass Antiqua:regular', 'label'=>Mage::helper('ExtraConfig')->__('Glass Antiqua')),
array('value'=>'Glegoo:regular', 'label'=>Mage::helper('ExtraConfig')->__('Glegoo')),
array('value'=>'Gloria Hallelujah:regular', 'label'=>Mage::helper('ExtraConfig')->__('Gloria Hallelujah')),
array('value'=>'Goblin One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Goblin One')),
array('value'=>'Gochi Hand:regular', 'label'=>Mage::helper('ExtraConfig')->__('Gochi Hand')),
array('value'=>'Gorditas:regular,700', 'label'=>Mage::helper('ExtraConfig')->__('Gorditas')),
array('value'=>'Goudy Bookletter 1911:regular', 'label'=>Mage::helper('ExtraConfig')->__('Goudy Bookletter 1911')),
array('value'=>'Graduate:regular', 'label'=>Mage::helper('ExtraConfig')->__('Graduate')),
array('value'=>'Grand Hotel:regular', 'label'=>Mage::helper('ExtraConfig')->__('Grand Hotel')),
array('value'=>'Gravitas One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Gravitas One')),
array('value'=>'Great Vibes:regular', 'label'=>Mage::helper('ExtraConfig')->__('Great Vibes')),
array('value'=>'Griffy:regular', 'label'=>Mage::helper('ExtraConfig')->__('Griffy')),
array('value'=>'Gruppo:regular', 'label'=>Mage::helper('ExtraConfig')->__('Gruppo')),
array('value'=>'Gudea:regular,italic,700', 'label'=>Mage::helper('ExtraConfig')->__('Gudea')),
array('value'=>'Habibi:regular', 'label'=>Mage::helper('ExtraConfig')->__('Habibi')),
array('value'=>'Hammersmith One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Hammersmith One')),
array('value'=>'Hanalei:regular', 'label'=>Mage::helper('ExtraConfig')->__('Hanalei')),
array('value'=>'Hanalei Fill:regular', 'label'=>Mage::helper('ExtraConfig')->__('Hanalei Fill')),
array('value'=>'Handlee:regular', 'label'=>Mage::helper('ExtraConfig')->__('Handlee')),
array('value'=>'Hanuman:regular,700', 'label'=>Mage::helper('ExtraConfig')->__('Hanuman')),
array('value'=>'Happy Monkey:regular', 'label'=>Mage::helper('ExtraConfig')->__('Happy Monkey')),
array('value'=>'Headland One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Headland One')),
array('value'=>'Henny Penny:regular', 'label'=>Mage::helper('ExtraConfig')->__('Henny Penny')),
array('value'=>'Herr Von Muellerhoff:regular', 'label'=>Mage::helper('ExtraConfig')->__('Herr Von Muellerhoff')),
array('value'=>'Holtwood One SC:regular', 'label'=>Mage::helper('ExtraConfig')->__('Holtwood One SC')),
array('value'=>'Homemade Apple:regular', 'label'=>Mage::helper('ExtraConfig')->__('Homemade Apple')),
array('value'=>'Homenaje:regular', 'label'=>Mage::helper('ExtraConfig')->__('Homenaje')),
array('value'=>'IM Fell DW Pica:regular,italic', 'label'=>Mage::helper('ExtraConfig')->__('IM Fell DW Pica')),
array('value'=>'IM Fell DW Pica SC:regular', 'label'=>Mage::helper('ExtraConfig')->__('IM Fell DW Pica SC')),
array('value'=>'IM Fell Double Pica:regular,italic', 'label'=>Mage::helper('ExtraConfig')->__('IM Fell Double Pica')),
array('value'=>'IM Fell Double Pica SC:regular', 'label'=>Mage::helper('ExtraConfig')->__('IM Fell Double Pica SC')),
array('value'=>'IM Fell English:regular,italic', 'label'=>Mage::helper('ExtraConfig')->__('IM Fell English')),
array('value'=>'IM Fell English SC:regular', 'label'=>Mage::helper('ExtraConfig')->__('IM Fell English SC')),
array('value'=>'IM Fell French Canon:regular,italic', 'label'=>Mage::helper('ExtraConfig')->__('IM Fell French Canon')),
array('value'=>'IM Fell French Canon SC:regular', 'label'=>Mage::helper('ExtraConfig')->__('IM Fell French Canon SC')),
array('value'=>'IM Fell Great Primer:regular,italic', 'label'=>Mage::helper('ExtraConfig')->__('IM Fell Great Primer')),
array('value'=>'IM Fell Great Primer SC:regular', 'label'=>Mage::helper('ExtraConfig')->__('IM Fell Great Primer SC')),
array('value'=>'Iceberg:regular', 'label'=>Mage::helper('ExtraConfig')->__('Iceberg')),
array('value'=>'Iceland:regular', 'label'=>Mage::helper('ExtraConfig')->__('Iceland')),
array('value'=>'Imprima:regular', 'label'=>Mage::helper('ExtraConfig')->__('Imprima')),
array('value'=>'Inconsolata:regular,700', 'label'=>Mage::helper('ExtraConfig')->__('Inconsolata')),
array('value'=>'Inder:regular', 'label'=>Mage::helper('ExtraConfig')->__('Inder')),
array('value'=>'Indie Flower:regular', 'label'=>Mage::helper('ExtraConfig')->__('Indie Flower')),
array('value'=>'Inika:regular,700', 'label'=>Mage::helper('ExtraConfig')->__('Inika')),
array('value'=>'Irish Grover:regular', 'label'=>Mage::helper('ExtraConfig')->__('Irish Grover')),
array('value'=>'Istok Web:regular,italic,700,700italic', 'label'=>Mage::helper('ExtraConfig')->__('Istok Web')),
array('value'=>'Italiana:regular', 'label'=>Mage::helper('ExtraConfig')->__('Italiana')),
array('value'=>'Italianno:regular', 'label'=>Mage::helper('ExtraConfig')->__('Italianno')),
array('value'=>'Jacques Francois:regular', 'label'=>Mage::helper('ExtraConfig')->__('Jacques Francois')),
array('value'=>'Jacques Francois Shadow:regular', 'label'=>Mage::helper('ExtraConfig')->__('Jacques Francois Shadow')),
array('value'=>'Jim Nightshade:regular', 'label'=>Mage::helper('ExtraConfig')->__('Jim Nightshade')),
array('value'=>'Jockey One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Jockey One')),
array('value'=>'Jolly Lodger:regular', 'label'=>Mage::helper('ExtraConfig')->__('Jolly Lodger')),
array('value'=>'Josefin Sans:100,100italic,300,300italic,regular,italic,600,600italic,700,700italic', 'label'=>Mage::helper('ExtraConfig')->__('Josefin Sans')),
array('value'=>'Josefin Slab:100,100italic,300,300italic,regular,italic,600,600italic,700,700italic', 'label'=>Mage::helper('ExtraConfig')->__('Josefin Slab')),
array('value'=>'Joti One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Joti One')),
array('value'=>'Judson:regular,italic,700', 'label'=>Mage::helper('ExtraConfig')->__('Judson')),
array('value'=>'Julee:regular', 'label'=>Mage::helper('ExtraConfig')->__('Julee')),
array('value'=>'Julius Sans One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Julius Sans One')),
array('value'=>'Junge:regular', 'label'=>Mage::helper('ExtraConfig')->__('Junge')),
array('value'=>'Jura:300,regular,500,600', 'label'=>Mage::helper('ExtraConfig')->__('Jura')),
array('value'=>'Just Another Hand:regular', 'label'=>Mage::helper('ExtraConfig')->__('Just Another Hand')),
array('value'=>'Just Me Again Down Here:regular', 'label'=>Mage::helper('ExtraConfig')->__('Just Me Again Down Here')),
array('value'=>'Kameron:regular,700', 'label'=>Mage::helper('ExtraConfig')->__('Kameron')),
array('value'=>'Karla:regular,italic,700,700italic', 'label'=>Mage::helper('ExtraConfig')->__('Karla')),
array('value'=>'Kaushan Script:regular', 'label'=>Mage::helper('ExtraConfig')->__('Kaushan Script')),
array('value'=>'Kavoon:regular', 'label'=>Mage::helper('ExtraConfig')->__('Kavoon')),
array('value'=>'Keania One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Keania One')),
array('value'=>'Kelly Slab:regular', 'label'=>Mage::helper('ExtraConfig')->__('Kelly Slab')),
array('value'=>'Kenia:regular', 'label'=>Mage::helper('ExtraConfig')->__('Kenia')),
array('value'=>'Khmer:regular', 'label'=>Mage::helper('ExtraConfig')->__('Khmer')),
array('value'=>'Kite One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Kite One')),
array('value'=>'Knewave:regular', 'label'=>Mage::helper('ExtraConfig')->__('Knewave')),
array('value'=>'Kotta One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Kotta One')),
array('value'=>'Koulen:regular', 'label'=>Mage::helper('ExtraConfig')->__('Koulen')),
array('value'=>'Kranky:regular', 'label'=>Mage::helper('ExtraConfig')->__('Kranky')),
array('value'=>'Kreon:300,regular,700', 'label'=>Mage::helper('ExtraConfig')->__('Kreon')),
array('value'=>'Kristi:regular', 'label'=>Mage::helper('ExtraConfig')->__('Kristi')),
array('value'=>'Krona One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Krona One')),
array('value'=>'La Belle Aurore:regular', 'label'=>Mage::helper('ExtraConfig')->__('La Belle Aurore')),
array('value'=>'Lancelot:regular', 'label'=>Mage::helper('ExtraConfig')->__('Lancelot')),
array('value'=>'Lato:100,100italic,300,300italic,regular,italic,700,700italic,900,900italic', 'label'=>Mage::helper('ExtraConfig')->__('Lato')),
array('value'=>'League Script:regular', 'label'=>Mage::helper('ExtraConfig')->__('League Script')),
array('value'=>'Leckerli One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Leckerli One')),
array('value'=>'Ledger:regular', 'label'=>Mage::helper('ExtraConfig')->__('Ledger')),
array('value'=>'Lekton:regular,italic,700', 'label'=>Mage::helper('ExtraConfig')->__('Lekton')),
array('value'=>'Lemon:regular', 'label'=>Mage::helper('ExtraConfig')->__('Lemon')),
array('value'=>'Libre Baskerville:regular,italic,700', 'label'=>Mage::helper('ExtraConfig')->__('Libre Baskerville')),
array('value'=>'Life Savers:regular,700', 'label'=>Mage::helper('ExtraConfig')->__('Life Savers')),
array('value'=>'Lilita One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Lilita One')),
array('value'=>'Limelight:regular', 'label'=>Mage::helper('ExtraConfig')->__('Limelight')),
array('value'=>'Linden Hill:regular,italic', 'label'=>Mage::helper('ExtraConfig')->__('Linden Hill')),
array('value'=>'Lobster:regular', 'label'=>Mage::helper('ExtraConfig')->__('Lobster')),
array('value'=>'Lobster Two:regular,italic,700,700italic', 'label'=>Mage::helper('ExtraConfig')->__('Lobster Two')),
array('value'=>'Londrina Outline:regular', 'label'=>Mage::helper('ExtraConfig')->__('Londrina Outline')),
array('value'=>'Londrina Shadow:regular', 'label'=>Mage::helper('ExtraConfig')->__('Londrina Shadow')),
array('value'=>'Londrina Sketch:regular', 'label'=>Mage::helper('ExtraConfig')->__('Londrina Sketch')),
array('value'=>'Londrina Solid:regular', 'label'=>Mage::helper('ExtraConfig')->__('Londrina Solid')),
array('value'=>'Lora:regular,italic,700,700italic', 'label'=>Mage::helper('ExtraConfig')->__('Lora')),
array('value'=>'Love Ya Like A Sister:regular', 'label'=>Mage::helper('ExtraConfig')->__('Love Ya Like A Sister')),
array('value'=>'Loved by the King:regular', 'label'=>Mage::helper('ExtraConfig')->__('Loved by the King')),
array('value'=>'Lovers Quarrel:regular', 'label'=>Mage::helper('ExtraConfig')->__('Lovers Quarrel')),
array('value'=>'Luckiest Guy:regular', 'label'=>Mage::helper('ExtraConfig')->__('Luckiest Guy')),
array('value'=>'Lusitana:regular,700', 'label'=>Mage::helper('ExtraConfig')->__('Lusitana')),
array('value'=>'Lustria:regular', 'label'=>Mage::helper('ExtraConfig')->__('Lustria')),
array('value'=>'Macondo:regular', 'label'=>Mage::helper('ExtraConfig')->__('Macondo')),
array('value'=>'Macondo Swash Caps:regular', 'label'=>Mage::helper('ExtraConfig')->__('Macondo Swash Caps')),
array('value'=>'Magra:regular,700', 'label'=>Mage::helper('ExtraConfig')->__('Magra')),
array('value'=>'Maiden Orange:regular', 'label'=>Mage::helper('ExtraConfig')->__('Maiden Orange')),
array('value'=>'Mako:regular', 'label'=>Mage::helper('ExtraConfig')->__('Mako')),
array('value'=>'Marcellus:regular', 'label'=>Mage::helper('ExtraConfig')->__('Marcellus')),
array('value'=>'Marcellus SC:regular', 'label'=>Mage::helper('ExtraConfig')->__('Marcellus SC')),
array('value'=>'Marck Script:regular', 'label'=>Mage::helper('ExtraConfig')->__('Marck Script')),
array('value'=>'Margarine:regular', 'label'=>Mage::helper('ExtraConfig')->__('Margarine')),
array('value'=>'Marko One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Marko One')),
array('value'=>'Marmelad:regular', 'label'=>Mage::helper('ExtraConfig')->__('Marmelad')),
array('value'=>'Marvel:regular,italic,700,700italic', 'label'=>Mage::helper('ExtraConfig')->__('Marvel')),
array('value'=>'Mate:regular,italic', 'label'=>Mage::helper('ExtraConfig')->__('Mate')),
array('value'=>'Mate SC:regular', 'label'=>Mage::helper('ExtraConfig')->__('Mate SC')),
array('value'=>'Maven Pro:regular,500,700,900', 'label'=>Mage::helper('ExtraConfig')->__('Maven Pro')),
array('value'=>'McLaren:regular', 'label'=>Mage::helper('ExtraConfig')->__('McLaren')),
array('value'=>'Meddon:regular', 'label'=>Mage::helper('ExtraConfig')->__('Meddon')),
array('value'=>'MedievalSharp:regular', 'label'=>Mage::helper('ExtraConfig')->__('MedievalSharp')),
array('value'=>'Medula One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Medula One')),
array('value'=>'Megrim:regular', 'label'=>Mage::helper('ExtraConfig')->__('Megrim')),
array('value'=>'Meie Script:regular', 'label'=>Mage::helper('ExtraConfig')->__('Meie Script')),
array('value'=>'Merienda:regular,700', 'label'=>Mage::helper('ExtraConfig')->__('Merienda')),
array('value'=>'Merienda One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Merienda One')),
array('value'=>'Merriweather:300,regular,700,900', 'label'=>Mage::helper('ExtraConfig')->__('Merriweather')),
array('value'=>'Metal:regular', 'label'=>Mage::helper('ExtraConfig')->__('Metal')),
array('value'=>'Metal Mania:regular', 'label'=>Mage::helper('ExtraConfig')->__('Metal Mania')),
array('value'=>'Metamorphous:regular', 'label'=>Mage::helper('ExtraConfig')->__('Metamorphous')),
array('value'=>'Metrophobic:regular', 'label'=>Mage::helper('ExtraConfig')->__('Metrophobic')),
array('value'=>'Michroma:regular', 'label'=>Mage::helper('ExtraConfig')->__('Michroma')),
array('value'=>'Milonga:regular', 'label'=>Mage::helper('ExtraConfig')->__('Milonga')),
array('value'=>'Miltonian:regular', 'label'=>Mage::helper('ExtraConfig')->__('Miltonian')),
array('value'=>'Miltonian Tattoo:regular', 'label'=>Mage::helper('ExtraConfig')->__('Miltonian Tattoo')),
array('value'=>'Miniver:regular', 'label'=>Mage::helper('ExtraConfig')->__('Miniver')),
array('value'=>'Miss Fajardose:regular', 'label'=>Mage::helper('ExtraConfig')->__('Miss Fajardose')),
array('value'=>'Modern Antiqua:regular', 'label'=>Mage::helper('ExtraConfig')->__('Modern Antiqua')),
array('value'=>'Molengo:regular', 'label'=>Mage::helper('ExtraConfig')->__('Molengo')),
array('value'=>'Molle:italic', 'label'=>Mage::helper('ExtraConfig')->__('Molle')),
array('value'=>'Monda:regular,700', 'label'=>Mage::helper('ExtraConfig')->__('Monda')),
array('value'=>'Monofett:regular', 'label'=>Mage::helper('ExtraConfig')->__('Monofett')),
array('value'=>'Monoton:regular', 'label'=>Mage::helper('ExtraConfig')->__('Monoton')),
array('value'=>'Monsieur La Doulaise:regular', 'label'=>Mage::helper('ExtraConfig')->__('Monsieur La Doulaise')),
array('value'=>'Montaga:regular', 'label'=>Mage::helper('ExtraConfig')->__('Montaga')),
array('value'=>'Montez:regular', 'label'=>Mage::helper('ExtraConfig')->__('Montez')),
array('value'=>'Montserrat:regular,700', 'label'=>Mage::helper('ExtraConfig')->__('Montserrat')),
array('value'=>'Montserrat Alternates:regular,700', 'label'=>Mage::helper('ExtraConfig')->__('Montserrat Alternates')),
array('value'=>'Montserrat Subrayada:regular,700', 'label'=>Mage::helper('ExtraConfig')->__('Montserrat Subrayada')),
array('value'=>'Moul:regular', 'label'=>Mage::helper('ExtraConfig')->__('Moul')),
array('value'=>'Moulpali:regular', 'label'=>Mage::helper('ExtraConfig')->__('Moulpali')),
array('value'=>'Mountains of Christmas:regular,700', 'label'=>Mage::helper('ExtraConfig')->__('Mountains of Christmas')),
array('value'=>'Mouse Memoirs:regular', 'label'=>Mage::helper('ExtraConfig')->__('Mouse Memoirs')),
array('value'=>'Mr Bedfort:regular', 'label'=>Mage::helper('ExtraConfig')->__('Mr Bedfort')),
array('value'=>'Mr Dafoe:regular', 'label'=>Mage::helper('ExtraConfig')->__('Mr Dafoe')),
array('value'=>'Mr De Haviland:regular', 'label'=>Mage::helper('ExtraConfig')->__('Mr De Haviland')),
array('value'=>'Mrs Saint Delafield:regular', 'label'=>Mage::helper('ExtraConfig')->__('Mrs Saint Delafield')),
array('value'=>'Mrs Sheppards:regular', 'label'=>Mage::helper('ExtraConfig')->__('Mrs Sheppards')),
array('value'=>'Muli:300,300italic,regular,italic', 'label'=>Mage::helper('ExtraConfig')->__('Muli')),
array('value'=>'Mystery Quest:regular', 'label'=>Mage::helper('ExtraConfig')->__('Mystery Quest')),
array('value'=>'Neucha:regular', 'label'=>Mage::helper('ExtraConfig')->__('Neucha')),
array('value'=>'Neuton:200,300,regular,italic,700,800', 'label'=>Mage::helper('ExtraConfig')->__('Neuton')),
array('value'=>'New Rocker:regular', 'label'=>Mage::helper('ExtraConfig')->__('New Rocker')),
array('value'=>'News Cycle:regular,700', 'label'=>Mage::helper('ExtraConfig')->__('News Cycle')),
array('value'=>'Niconne:regular', 'label'=>Mage::helper('ExtraConfig')->__('Niconne')),
array('value'=>'Nixie One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Nixie One')),
array('value'=>'Nobile:regular,italic,700,700italic', 'label'=>Mage::helper('ExtraConfig')->__('Nobile')),
array('value'=>'Nokora:regular,700', 'label'=>Mage::helper('ExtraConfig')->__('Nokora')),
array('value'=>'Norican:regular', 'label'=>Mage::helper('ExtraConfig')->__('Norican')),
array('value'=>'Nosifer:regular', 'label'=>Mage::helper('ExtraConfig')->__('Nosifer')),
array('value'=>'Nothing You Could Do:regular', 'label'=>Mage::helper('ExtraConfig')->__('Nothing You Could Do')),
array('value'=>'Noticia Text:regular,italic,700,700italic', 'label'=>Mage::helper('ExtraConfig')->__('Noticia Text')),
array('value'=>'Nova Cut:regular', 'label'=>Mage::helper('ExtraConfig')->__('Nova Cut')),
array('value'=>'Nova Flat:regular', 'label'=>Mage::helper('ExtraConfig')->__('Nova Flat')),
array('value'=>'Nova Mono:regular', 'label'=>Mage::helper('ExtraConfig')->__('Nova Mono')),
array('value'=>'Nova Oval:regular', 'label'=>Mage::helper('ExtraConfig')->__('Nova Oval')),
array('value'=>'Nova Round:regular', 'label'=>Mage::helper('ExtraConfig')->__('Nova Round')),
array('value'=>'Nova Script:regular', 'label'=>Mage::helper('ExtraConfig')->__('Nova Script')),
array('value'=>'Nova Slim:regular', 'label'=>Mage::helper('ExtraConfig')->__('Nova Slim')),
array('value'=>'Nova Square:regular', 'label'=>Mage::helper('ExtraConfig')->__('Nova Square')),
array('value'=>'Numans:regular', 'label'=>Mage::helper('ExtraConfig')->__('Numans')),
array('value'=>'Nunito:300,regular,700', 'label'=>Mage::helper('ExtraConfig')->__('Nunito')),
array('value'=>'Odor Mean Chey:regular', 'label'=>Mage::helper('ExtraConfig')->__('Odor Mean Chey')),
array('value'=>'Offside:regular', 'label'=>Mage::helper('ExtraConfig')->__('Offside')),
array('value'=>'Old Standard TT:regular,italic,700', 'label'=>Mage::helper('ExtraConfig')->__('Old Standard TT')),
array('value'=>'Oldenburg:regular', 'label'=>Mage::helper('ExtraConfig')->__('Oldenburg')),
array('value'=>'Oleo Script:regular,700', 'label'=>Mage::helper('ExtraConfig')->__('Oleo Script')),
array('value'=>'Oleo Script Swash Caps:regular,700', 'label'=>Mage::helper('ExtraConfig')->__('Oleo Script Swash Caps')),
array('value'=>'Open Sans:300,300italic,regular,italic,600,600italic,700,700italic,800,800italic', 'label'=>Mage::helper('ExtraConfig')->__('Open Sans')),
array('value'=>'Open Sans Condensed:300,300italic,700', 'label'=>Mage::helper('ExtraConfig')->__('Open Sans Condensed')),
array('value'=>'Oranienbaum:regular', 'label'=>Mage::helper('ExtraConfig')->__('Oranienbaum')),
array('value'=>'Orbitron:regular,500,700,900', 'label'=>Mage::helper('ExtraConfig')->__('Orbitron')),
array('value'=>'Oregano:regular,italic', 'label'=>Mage::helper('ExtraConfig')->__('Oregano')),
array('value'=>'Orienta:regular', 'label'=>Mage::helper('ExtraConfig')->__('Orienta')),
array('value'=>'Original Surfer:regular', 'label'=>Mage::helper('ExtraConfig')->__('Original Surfer')),
array('value'=>'Oswald:300,regular,700', 'label'=>Mage::helper('ExtraConfig')->__('Oswald')),
array('value'=>'Over the Rainbow:regular', 'label'=>Mage::helper('ExtraConfig')->__('Over the Rainbow')),
array('value'=>'Overlock:regular,italic,700,700italic,900,900italic', 'label'=>Mage::helper('ExtraConfig')->__('Overlock')),
array('value'=>'Overlock SC:regular', 'label'=>Mage::helper('ExtraConfig')->__('Overlock SC')),
array('value'=>'Ovo:regular', 'label'=>Mage::helper('ExtraConfig')->__('Ovo')),
array('value'=>'Oxygen:300,regular,700', 'label'=>Mage::helper('ExtraConfig')->__('Oxygen')),
array('value'=>'Oxygen Mono:regular', 'label'=>Mage::helper('ExtraConfig')->__('Oxygen Mono')),
array('value'=>'PT Mono:regular', 'label'=>Mage::helper('ExtraConfig')->__('PT Mono')),
array('value'=>'PT Sans:regular,italic,700,700italic', 'label'=>Mage::helper('ExtraConfig')->__('PT Sans')),
array('value'=>'PT Sans Caption:regular,700', 'label'=>Mage::helper('ExtraConfig')->__('PT Sans Caption')),
array('value'=>'PT Sans Narrow:regular,700', 'label'=>Mage::helper('ExtraConfig')->__('PT Sans Narrow')),
array('value'=>'PT Serif:regular,italic,700,700italic', 'label'=>Mage::helper('ExtraConfig')->__('PT Serif')),
array('value'=>'PT Serif Caption:regular,italic', 'label'=>Mage::helper('ExtraConfig')->__('PT Serif Caption')),
array('value'=>'Pacifico:regular', 'label'=>Mage::helper('ExtraConfig')->__('Pacifico')),
array('value'=>'Paprika:regular', 'label'=>Mage::helper('ExtraConfig')->__('Paprika')),
array('value'=>'Parisienne:regular', 'label'=>Mage::helper('ExtraConfig')->__('Parisienne')),
array('value'=>'Passero One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Passero One')),
array('value'=>'Passion One:regular,700,900', 'label'=>Mage::helper('ExtraConfig')->__('Passion One')),
array('value'=>'Patrick Hand:regular', 'label'=>Mage::helper('ExtraConfig')->__('Patrick Hand')),
array('value'=>'Patua One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Patua One')),
array('value'=>'Paytone One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Paytone One')),
array('value'=>'Peralta:regular', 'label'=>Mage::helper('ExtraConfig')->__('Peralta')),
array('value'=>'Permanent Marker:regular', 'label'=>Mage::helper('ExtraConfig')->__('Permanent Marker')),
array('value'=>'Petit Formal Script:regular', 'label'=>Mage::helper('ExtraConfig')->__('Petit Formal Script')),
array('value'=>'Petrona:regular', 'label'=>Mage::helper('ExtraConfig')->__('Petrona')),
array('value'=>'Philosopher:regular,italic,700,700italic', 'label'=>Mage::helper('ExtraConfig')->__('Philosopher')),
array('value'=>'Piedra:regular', 'label'=>Mage::helper('ExtraConfig')->__('Piedra')),
array('value'=>'Pinyon Script:regular', 'label'=>Mage::helper('ExtraConfig')->__('Pinyon Script')),
array('value'=>'Pirata One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Pirata One')),
array('value'=>'Plaster:regular', 'label'=>Mage::helper('ExtraConfig')->__('Plaster')),
array('value'=>'Play:regular,700', 'label'=>Mage::helper('ExtraConfig')->__('Play')),
array('value'=>'Playball:regular', 'label'=>Mage::helper('ExtraConfig')->__('Playball')),
array('value'=>'Playfair Display:regular,italic,700,700italic,900,900italic', 'label'=>Mage::helper('ExtraConfig')->__('Playfair Display')),
array('value'=>'Playfair Display SC:regular,italic,700,700italic,900,900italic', 'label'=>Mage::helper('ExtraConfig')->__('Playfair Display SC')),
array('value'=>'Podkova:regular,700', 'label'=>Mage::helper('ExtraConfig')->__('Podkova')),
array('value'=>'Poiret One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Poiret One')),
array('value'=>'Poller One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Poller One')),
array('value'=>'Poly:regular,italic', 'label'=>Mage::helper('ExtraConfig')->__('Poly')),
array('value'=>'Pompiere:regular', 'label'=>Mage::helper('ExtraConfig')->__('Pompiere')),
array('value'=>'Pontano Sans:regular', 'label'=>Mage::helper('ExtraConfig')->__('Pontano Sans')),
array('value'=>'Port Lligat Sans:regular', 'label'=>Mage::helper('ExtraConfig')->__('Port Lligat Sans')),
array('value'=>'Port Lligat Slab:regular', 'label'=>Mage::helper('ExtraConfig')->__('Port Lligat Slab')),
array('value'=>'Prata:regular', 'label'=>Mage::helper('ExtraConfig')->__('Prata')),
array('value'=>'Preahvihear:regular', 'label'=>Mage::helper('ExtraConfig')->__('Preahvihear')),
array('value'=>'Press Start 2P:regular', 'label'=>Mage::helper('ExtraConfig')->__('Press Start 2P')),
array('value'=>'Princess Sofia:regular', 'label'=>Mage::helper('ExtraConfig')->__('Princess Sofia')),
array('value'=>'Prociono:regular', 'label'=>Mage::helper('ExtraConfig')->__('Prociono')),
array('value'=>'Prosto One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Prosto One')),
array('value'=>'Puritan:regular,italic,700,700italic', 'label'=>Mage::helper('ExtraConfig')->__('Puritan')),
array('value'=>'Purple Purse:regular', 'label'=>Mage::helper('ExtraConfig')->__('Purple Purse')),
array('value'=>'Quando:regular', 'label'=>Mage::helper('ExtraConfig')->__('Quando')),
array('value'=>'Quantico:regular,italic,700,700italic', 'label'=>Mage::helper('ExtraConfig')->__('Quantico')),
array('value'=>'Quattrocento:regular,700', 'label'=>Mage::helper('ExtraConfig')->__('Quattrocento')),
array('value'=>'Quattrocento Sans:regular,italic,700,700italic', 'label'=>Mage::helper('ExtraConfig')->__('Quattrocento Sans')),
array('value'=>'Questrial:regular', 'label'=>Mage::helper('ExtraConfig')->__('Questrial')),
array('value'=>'Quicksand:300,regular,700', 'label'=>Mage::helper('ExtraConfig')->__('Quicksand')),
array('value'=>'Quintessential:regular', 'label'=>Mage::helper('ExtraConfig')->__('Quintessential')),
array('value'=>'Qwigley:regular', 'label'=>Mage::helper('ExtraConfig')->__('Qwigley')),
array('value'=>'Racing Sans One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Racing Sans One')),
array('value'=>'Radley:regular,italic', 'label'=>Mage::helper('ExtraConfig')->__('Radley')),
array('value'=>'Raleway:100,200,300,regular,500,600,700,800,900', 'label'=>Mage::helper('ExtraConfig')->__('Raleway')),
array('value'=>'Raleway Dots:regular', 'label'=>Mage::helper('ExtraConfig')->__('Raleway Dots')),
array('value'=>'Rambla:regular,italic,700,700italic', 'label'=>Mage::helper('ExtraConfig')->__('Rambla')),
array('value'=>'Rammetto One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Rammetto One')),
array('value'=>'Ranchers:regular', 'label'=>Mage::helper('ExtraConfig')->__('Ranchers')),
array('value'=>'Rancho:regular', 'label'=>Mage::helper('ExtraConfig')->__('Rancho')),
array('value'=>'Rationale:regular', 'label'=>Mage::helper('ExtraConfig')->__('Rationale')),
array('value'=>'Redressed:regular', 'label'=>Mage::helper('ExtraConfig')->__('Redressed')),
array('value'=>'Reenie Beanie:regular', 'label'=>Mage::helper('ExtraConfig')->__('Reenie Beanie')),
array('value'=>'Revalia:regular', 'label'=>Mage::helper('ExtraConfig')->__('Revalia')),
array('value'=>'Ribeye:regular', 'label'=>Mage::helper('ExtraConfig')->__('Ribeye')),
array('value'=>'Ribeye Marrow:regular', 'label'=>Mage::helper('ExtraConfig')->__('Ribeye Marrow')),
array('value'=>'Righteous:regular', 'label'=>Mage::helper('ExtraConfig')->__('Righteous')),
array('value'=>'Risque:regular', 'label'=>Mage::helper('ExtraConfig')->__('Risque')),
array('value'=>'Roboto:100,100italic,300,300italic,regular,italic,500,500italic,700,700italic,900,900italic', 'label'=>Mage::helper('ExtraConfig')->__('Roboto')),
array('value'=>'Roboto Condensed:300,300italic,regular,italic,700,700italic', 'label'=>Mage::helper('ExtraConfig')->__('Roboto Condensed')),
array('value'=>'Rochester:regular', 'label'=>Mage::helper('ExtraConfig')->__('Rochester')),
array('value'=>'Rock Salt:regular', 'label'=>Mage::helper('ExtraConfig')->__('Rock Salt')),
array('value'=>'Rokkitt:regular,700', 'label'=>Mage::helper('ExtraConfig')->__('Rokkitt')),
array('value'=>'Romanesco:regular', 'label'=>Mage::helper('ExtraConfig')->__('Romanesco')),
array('value'=>'Ropa Sans:regular,italic', 'label'=>Mage::helper('ExtraConfig')->__('Ropa Sans')),
array('value'=>'Rosario:regular,italic,700,700italic', 'label'=>Mage::helper('ExtraConfig')->__('Rosario')),
array('value'=>'Rosarivo:regular,italic', 'label'=>Mage::helper('ExtraConfig')->__('Rosarivo')),
array('value'=>'Rouge Script:regular', 'label'=>Mage::helper('ExtraConfig')->__('Rouge Script')),
array('value'=>'Ruda:regular,700,900', 'label'=>Mage::helper('ExtraConfig')->__('Ruda')),
array('value'=>'Rufina:regular,700', 'label'=>Mage::helper('ExtraConfig')->__('Rufina')),
array('value'=>'Ruge Boogie:regular', 'label'=>Mage::helper('ExtraConfig')->__('Ruge Boogie')),
array('value'=>'Ruluko:regular', 'label'=>Mage::helper('ExtraConfig')->__('Ruluko')),
array('value'=>'Rum Raisin:regular', 'label'=>Mage::helper('ExtraConfig')->__('Rum Raisin')),
array('value'=>'Ruslan Display:regular', 'label'=>Mage::helper('ExtraConfig')->__('Ruslan Display')),
array('value'=>'Russo One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Russo One')),
array('value'=>'Ruthie:regular', 'label'=>Mage::helper('ExtraConfig')->__('Ruthie')),
array('value'=>'Rye:regular', 'label'=>Mage::helper('ExtraConfig')->__('Rye')),
array('value'=>'Sacramento:regular', 'label'=>Mage::helper('ExtraConfig')->__('Sacramento')),
array('value'=>'Sail:regular', 'label'=>Mage::helper('ExtraConfig')->__('Sail')),
array('value'=>'Salsa:regular', 'label'=>Mage::helper('ExtraConfig')->__('Salsa')),
array('value'=>'Sanchez:regular,italic', 'label'=>Mage::helper('ExtraConfig')->__('Sanchez')),
array('value'=>'Sancreek:regular', 'label'=>Mage::helper('ExtraConfig')->__('Sancreek')),
array('value'=>'Sansita One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Sansita One')),
array('value'=>'Sarina:regular', 'label'=>Mage::helper('ExtraConfig')->__('Sarina')),
array('value'=>'Satisfy:regular', 'label'=>Mage::helper('ExtraConfig')->__('Satisfy')),
array('value'=>'Scada:regular,italic,700,700italic', 'label'=>Mage::helper('ExtraConfig')->__('Scada')),
array('value'=>'Schoolbell:regular', 'label'=>Mage::helper('ExtraConfig')->__('Schoolbell')),
array('value'=>'Seaweed Script:regular', 'label'=>Mage::helper('ExtraConfig')->__('Seaweed Script')),
array('value'=>'Sevillana:regular', 'label'=>Mage::helper('ExtraConfig')->__('Sevillana')),
array('value'=>'Seymour One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Seymour One')),
array('value'=>'Shadows Into Light:regular', 'label'=>Mage::helper('ExtraConfig')->__('Shadows Into Light')),
array('value'=>'Shadows Into Light Two:regular', 'label'=>Mage::helper('ExtraConfig')->__('Shadows Into Light Two')),
array('value'=>'Shanti:regular', 'label'=>Mage::helper('ExtraConfig')->__('Shanti')),
array('value'=>'Share:regular,italic,700,700italic', 'label'=>Mage::helper('ExtraConfig')->__('Share')),
array('value'=>'Share Tech:regular', 'label'=>Mage::helper('ExtraConfig')->__('Share Tech')),
array('value'=>'Share Tech Mono:regular', 'label'=>Mage::helper('ExtraConfig')->__('Share Tech Mono')),
array('value'=>'Shojumaru:regular', 'label'=>Mage::helper('ExtraConfig')->__('Shojumaru')),
array('value'=>'Short Stack:regular', 'label'=>Mage::helper('ExtraConfig')->__('Short Stack')),
array('value'=>'Siemreap:regular', 'label'=>Mage::helper('ExtraConfig')->__('Siemreap')),
array('value'=>'Sigmar One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Sigmar One')),
array('value'=>'Signika:300,regular,600,700', 'label'=>Mage::helper('ExtraConfig')->__('Signika')),
array('value'=>'Signika Negative:300,regular,600,700', 'label'=>Mage::helper('ExtraConfig')->__('Signika Negative')),
array('value'=>'Simonetta:regular,italic,900,900italic', 'label'=>Mage::helper('ExtraConfig')->__('Simonetta')),
array('value'=>'Sirin Stencil:regular', 'label'=>Mage::helper('ExtraConfig')->__('Sirin Stencil')),
array('value'=>'Six Caps:regular', 'label'=>Mage::helper('ExtraConfig')->__('Six Caps')),
array('value'=>'Skranji:regular,700', 'label'=>Mage::helper('ExtraConfig')->__('Skranji')),
array('value'=>'Slackey:regular', 'label'=>Mage::helper('ExtraConfig')->__('Slackey')),
array('value'=>'Smokum:regular', 'label'=>Mage::helper('ExtraConfig')->__('Smokum')),
array('value'=>'Smythe:regular', 'label'=>Mage::helper('ExtraConfig')->__('Smythe')),
array('value'=>'Sniglet:800', 'label'=>Mage::helper('ExtraConfig')->__('Sniglet')),
array('value'=>'Snippet:regular', 'label'=>Mage::helper('ExtraConfig')->__('Snippet')),
array('value'=>'Snowburst One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Snowburst One')),
array('value'=>'Sofadi One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Sofadi One')),
array('value'=>'Sofia:regular', 'label'=>Mage::helper('ExtraConfig')->__('Sofia')),
array('value'=>'Sonsie One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Sonsie One')),
array('value'=>'Sorts Mill Goudy:regular,italic', 'label'=>Mage::helper('ExtraConfig')->__('Sorts Mill Goudy')),
array('value'=>'Source Code Pro:200,300,regular,500,600,700,900', 'label'=>Mage::helper('ExtraConfig')->__('Source Code Pro')),
array('value'=>'Source Sans Pro:200,200italic,300,300italic,regular,italic,600,600italic,700,700italic,900,900italic', 'label'=>Mage::helper('ExtraConfig')->__('Source Sans Pro')),
array('value'=>'Special Elite:regular', 'label'=>Mage::helper('ExtraConfig')->__('Special Elite')),
array('value'=>'Spicy Rice:regular', 'label'=>Mage::helper('ExtraConfig')->__('Spicy Rice')),
array('value'=>'Spinnaker:regular', 'label'=>Mage::helper('ExtraConfig')->__('Spinnaker')),
array('value'=>'Spirax:regular', 'label'=>Mage::helper('ExtraConfig')->__('Spirax')),
array('value'=>'Squada One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Squada One')),
array('value'=>'Stalemate:regular', 'label'=>Mage::helper('ExtraConfig')->__('Stalemate')),
array('value'=>'Stalinist One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Stalinist One')),
array('value'=>'Stardos Stencil:regular,700', 'label'=>Mage::helper('ExtraConfig')->__('Stardos Stencil')),
array('value'=>'Stint Ultra Condensed:regular', 'label'=>Mage::helper('ExtraConfig')->__('Stint Ultra Condensed')),
array('value'=>'Stint Ultra Expanded:regular', 'label'=>Mage::helper('ExtraConfig')->__('Stint Ultra Expanded')),
array('value'=>'Stoke:300,regular', 'label'=>Mage::helper('ExtraConfig')->__('Stoke')),
array('value'=>'Strait:regular', 'label'=>Mage::helper('ExtraConfig')->__('Strait')),
array('value'=>'Sue Ellen Francisco:regular', 'label'=>Mage::helper('ExtraConfig')->__('Sue Ellen Francisco')),
array('value'=>'Sunshiney:regular', 'label'=>Mage::helper('ExtraConfig')->__('Sunshiney')),
array('value'=>'Supermercado One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Supermercado One')),
array('value'=>'Suwannaphum:regular', 'label'=>Mage::helper('ExtraConfig')->__('Suwannaphum')),
array('value'=>'Swanky and Moo Moo:regular', 'label'=>Mage::helper('ExtraConfig')->__('Swanky and Moo Moo')),
array('value'=>'Syncopate:regular,700', 'label'=>Mage::helper('ExtraConfig')->__('Syncopate')),
array('value'=>'Tangerine:regular,700', 'label'=>Mage::helper('ExtraConfig')->__('Tangerine')),
array('value'=>'Taprom:regular', 'label'=>Mage::helper('ExtraConfig')->__('Taprom')),
array('value'=>'Telex:regular', 'label'=>Mage::helper('ExtraConfig')->__('Telex')),
array('value'=>'Tenor Sans:regular', 'label'=>Mage::helper('ExtraConfig')->__('Tenor Sans')),
array('value'=>'Text Me One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Text Me One')),
array('value'=>'The Girl Next Door:regular', 'label'=>Mage::helper('ExtraConfig')->__('The Girl Next Door')),
array('value'=>'Tienne:regular,700,900', 'label'=>Mage::helper('ExtraConfig')->__('Tienne')),
array('value'=>'Tinos:regular,italic,700,700italic', 'label'=>Mage::helper('ExtraConfig')->__('Tinos')),
array('value'=>'Titan One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Titan One')),
array('value'=>'Titillium Web:200,200italic,300,300italic,regular,italic,600,600italic,700,700italic,900', 'label'=>Mage::helper('ExtraConfig')->__('Titillium Web')),
array('value'=>'Trade Winds:regular', 'label'=>Mage::helper('ExtraConfig')->__('Trade Winds')),
array('value'=>'Trocchi:regular', 'label'=>Mage::helper('ExtraConfig')->__('Trocchi')),
array('value'=>'Trochut:regular,italic,700', 'label'=>Mage::helper('ExtraConfig')->__('Trochut')),
array('value'=>'Trykker:regular', 'label'=>Mage::helper('ExtraConfig')->__('Trykker')),
array('value'=>'Tulpen One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Tulpen One')),
array('value'=>'Ubuntu:300,300italic,regular,italic,500,500italic,700,700italic', 'label'=>Mage::helper('ExtraConfig')->__('Ubuntu')),
array('value'=>'Ubuntu Condensed:regular', 'label'=>Mage::helper('ExtraConfig')->__('Ubuntu Condensed')),
array('value'=>'Ubuntu Mono:regular,italic,700,700italic', 'label'=>Mage::helper('ExtraConfig')->__('Ubuntu Mono')),
array('value'=>'Ultra:regular', 'label'=>Mage::helper('ExtraConfig')->__('Ultra')),
array('value'=>'Uncial Antiqua:regular', 'label'=>Mage::helper('ExtraConfig')->__('Uncial Antiqua')),
array('value'=>'Underdog:regular', 'label'=>Mage::helper('ExtraConfig')->__('Underdog')),
array('value'=>'Unica One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Unica One')),
array('value'=>'UnifrakturCook:700', 'label'=>Mage::helper('ExtraConfig')->__('UnifrakturCook')),
array('value'=>'UnifrakturMaguntia:regular', 'label'=>Mage::helper('ExtraConfig')->__('UnifrakturMaguntia')),
array('value'=>'Unkempt:regular,700', 'label'=>Mage::helper('ExtraConfig')->__('Unkempt')),
array('value'=>'Unlock:regular', 'label'=>Mage::helper('ExtraConfig')->__('Unlock')),
array('value'=>'Unna:regular', 'label'=>Mage::helper('ExtraConfig')->__('Unna')),
array('value'=>'VT323:regular', 'label'=>Mage::helper('ExtraConfig')->__('VT323')),
array('value'=>'Vampiro One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Vampiro One')),
array('value'=>'Varela:regular', 'label'=>Mage::helper('ExtraConfig')->__('Varela')),
array('value'=>'Varela Round:regular', 'label'=>Mage::helper('ExtraConfig')->__('Varela Round')),
array('value'=>'Vast Shadow:regular', 'label'=>Mage::helper('ExtraConfig')->__('Vast Shadow')),
array('value'=>'Vibur:regular', 'label'=>Mage::helper('ExtraConfig')->__('Vibur')),
array('value'=>'Vidaloka:regular', 'label'=>Mage::helper('ExtraConfig')->__('Vidaloka')),
array('value'=>'Viga:regular', 'label'=>Mage::helper('ExtraConfig')->__('Viga')),
array('value'=>'Voces:regular', 'label'=>Mage::helper('ExtraConfig')->__('Voces')),
array('value'=>'Volkhov:regular,italic,700,700italic', 'label'=>Mage::helper('ExtraConfig')->__('Volkhov')),
array('value'=>'Vollkorn:regular,italic,700,700italic', 'label'=>Mage::helper('ExtraConfig')->__('Vollkorn')),
array('value'=>'Voltaire:regular', 'label'=>Mage::helper('ExtraConfig')->__('Voltaire')),
array('value'=>'Waiting for the Sunrise:regular', 'label'=>Mage::helper('ExtraConfig')->__('Waiting for the Sunrise')),
array('value'=>'Wallpoet:regular', 'label'=>Mage::helper('ExtraConfig')->__('Wallpoet')),
array('value'=>'Walter Turncoat:regular', 'label'=>Mage::helper('ExtraConfig')->__('Walter Turncoat')),
array('value'=>'Warnes:regular', 'label'=>Mage::helper('ExtraConfig')->__('Warnes')),
array('value'=>'Wellfleet:regular', 'label'=>Mage::helper('ExtraConfig')->__('Wellfleet')),
array('value'=>'Wendy One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Wendy One')),
array('value'=>'Wire One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Wire One')),
array('value'=>'Yanone Kaffeesatz:200,300,regular,700', 'label'=>Mage::helper('ExtraConfig')->__('Yanone Kaffeesatz')),
array('value'=>'Yellowtail:regular', 'label'=>Mage::helper('ExtraConfig')->__('Yellowtail')),
array('value'=>'Yeseva One:regular', 'label'=>Mage::helper('ExtraConfig')->__('Yeseva One')),
array('value'=>'Yesteryear:regular', 'label'=>Mage::helper('ExtraConfig')->__('Yesteryear')),
array('value'=>'Zeyada:regular', 'label'=>Mage::helper('ExtraConfig')->__('Zeyada'))
   
        );
    }

}?>